stages:
  - test

test:
  stage: test
  tags:
    - docker
  script:
    - pip install --upgrade pip
    - pip install hatch
    - hatch test --cover
  coverage: 'TOTAL\s+[0-9]+\s+[0-9]+\s+[0-9]+\s+[0-9]+\s+([0-9]+)%'
