stages:
  - test
  - build
  - deploy
  - deploy_to_develop

test:
  stage: test
  tags:
    - docker
  script:
    - pip install --upgrade pip
    - pip install hatch hatch-vcs  # Install both hatch and hatch-vcs
    - hatch test --cover  # Run tests with coverage
  coverage: '/\s+(\d+%)$/'

build:
  stage: build
  tags:
    - docker
  script:
    - pip install --upgrade pip
    - pip install hatch hatch-vcs  # Install both hatch and hatch-vcs
    - hatch version  # Ensure versioning is based on Git tags
    - hatch build -t wheel  # Build the wheel, it will use the Git tag version
  artifacts:
    paths:
      - dist/*.whl  # Save the built wheel files as artifacts

deploy:
  stage: deploy
  only:
    - tags
  tags:
    - docker
  script:
    - echo "my-arithmetic-nphili02 deployment on stable servers"
    - ls -l dist/
    - cat dist/*

deploy_to_develop:
  stage: deploy_to_develop
  only:
    - develop
  tags:
    - docker
  script:
    - echo "my-arithmetic-nphili02 deployment on develop servers"
    - ls -l dist/  # Afficher le contenu du dossier dist
    - cat dist/*  # Afficher le contenu des fichiers .whl générés

