name: CI Workflow

on:
  push:
    branches:
      - main
      - develop
    tags:
      - '*'
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install hatch hatch-vcs

      - name: Run tests with coverage
        run: hatch test --cover

      - name: Upload coverage results
        if: success()
        run: |
          echo "Coverage: $(hatch test --cover)"

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install hatch hatch-vcs

      - name: Ensure versioning based on Git tags
        run: hatch version

      - name: Build wheel
        run: hatch build -t wheel

      - name: Upload built wheel as artifact
        uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: dist/*.whl

  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download built wheel artifact
        uses: actions/download-artifact@v3
        with:
          name: wheel

      - name: Deploy to stable servers
        run: |
          echo "my-arithmetic-nphili02 deployment on stable servers"
          ls -l dist/
          cat dist/*

  deploy_to_develop:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download built wheel artifact
        uses: actions/download-artifact@v3
        with:
          name: wheel

      - name: Deploy to develop servers
        run: |
          echo "my-arithmetic-nphili02 deployment on develop servers"
          ls -l dist/
          cat dist/*
